image: node:11.9.0-stretch

test:
  script:
    - npm install
    - ./bin/prepare-production.sh
    - ./bin/test.sh

release:
  only:
    - release@getto-systems-labo/upload/elm
  script:
    - ./bin/push_tags.sh
